services:

  backend:
    build: ./backend
    image: rimugames/backend
    container_name: backend
    env_file:
      - ./backend/.env
    ports:
      - "8080:8080"
    networks:
      - app-public
      - app-private
    depends_on:
      - elasticsearch
      - logstash
      - prometheus

  frontend:
    build: ./frontend
    image: rimugames/frontend
    container_name: frontend
    environment:
      - BACKEND_URL=http://backend:8080
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-public

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - app-private

  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.0
    container_name: logstash
    volumes:
      - ./docker/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch
    networks:
      - app-private

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.0
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - app-private
      - app-public

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - app-private

  grafana:
    image: grafana/grafana:9.4.0
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - app-private
      - app-public

volumes:
  es_data:
  grafana_data:

networks:
  app-public:
    driver: bridge
  app-private:
    driver: bridge
    internal: true
